    drop table ef_role if exists;

    drop table ef_user if exists;

    drop table ef_user_role if exists;
    
    create table ef_role (
        id bigint generated by default as identity,
        name varchar(255) not null unique,
        primary key (id)
    );

    create table ef_user (
        id bigint generated by default as identity,
        create_time timestamp,
        email varchar(255),
        login_name varchar(255) not null unique,
        name varchar(255),
        plain_password varchar(255),
        sha_password varchar(255),
        status varchar(255),
        primary key (id)
    );

    create table ef_user_role (
        user_id bigint not null,
        role_id bigint not null,
        primary key (user_id, role_id)
    );
    
    alter table ef_user_role 
        add constraint ef_user_role_uid_fk 
        foreign key (user_id) 
        references ef_user;

    alter table ef_user_role 
        add constraint ef_user_role_rid_fk 
        foreign key (role_id) 
        references ef_role;
